### ISSUE TITLE
Падает процесс при нажатии "About" и "Show daemon output"

### ISSUE THREAD

**Issue by avmaksimov** [slytomcat/yd-go#26]
Ubuntu 22.10.
Логи Debug ниже (личные данные заменены звёздочками).

**About**
```
yd-go11:35:49.516090 tools.go:135: I: Debugging enabled
yd-go11:35:49.520504 tools.go:94: D: cfg read: &{path:/home/andrei/.config/yd-go/default.cfg Conf:/home/andrei/.config/yandex-disk/config.cfg Theme:dark Notifications:true StartDaemon:true StopDaemon:false}
yd-go11:35:49.520512 yd.go:87: D: Local language is: en
yd-go11:35:49.521881 ydisk.go:204: D: yandex-disk executable is: /usr/bin/yandex-disk
yd-go11:35:49.521905 ydisk.go:171: D: Watch path added
yd-go11:35:49.521911 ydisk.go:218: D: New YDisk created and initialized. Path: /mnt/Data-s/Data/Yandex.Disk
yd-go11:35:49.521920 yd.go:165: D: event handler started
yd-go11:35:49.522005 ydisk.go:224: D: Event handler started
yd-go11:35:49.527708 ydisk.go:305: D: Daemon already started
yd-go11:35:49.622928 ydisk.go:246: D: Timer interval: 1
yd-go11:35:49.628352 ydisk.go:260: D: Change:  unknown > idle S true L 10 E false
yd-go11:35:49.628447 yd.go:283: D: Last synchronized length: 10
yd-go11:35:49.629478 yd.go:305: D: Change handled
yd-go11:35:51.623734 ydisk.go:246: D: Timer interval: 1
yd-go11:35:53.624906 ydisk.go:246: D: Timer interval: 2
yd-go11:35:57.445454 yd.go:100: D: Message: yd-go : yd-go is the panel indicator for Yandex.Disk daemon.

	Version: v.master-ce8e835

Copyleft 2017-2023 Sly_tom_cat (slytomcat@mail.ru)

	License: GPL v.3


yd-go11:35:57.461894 ydisk.go:232: D: Event handler exited
yd-go11:35:57.461923 panic.go:884: D: event handler exited.
panic: The name org.freedesktop.Notifications was not provided by any .service files

goroutine 39 [running]:
github.com/slytomcat/yd-go/notify.(*Notify).Send(0xc0001c20a0, {0x0?, 0x6a4200?}, {0x64fe35, 0x5}yd-go11:35:57.462103 tools.go:106: D: cfg saved: /home/andrei/.config/yd-go/default.cfg
, {0xc00059c140, 0x99})
	/home/runner/work/yd-go/yd-go/notify/notify.go:65 +0x2fd
main.onReady.func2({0x64fe35, 0x5}, {0xc00059c140, 0x99})
	/home/runner/work/yd-go/yd-go/yd.go:101 +0x10d
main.eventHandler(0xc0001e2000, 0xc0001860c0, 0xc0001c2140, 0xc0001c20a0)
	/home/runner/work/yd-go/yd-go/yd.go:229 +0xc7a
created by main.onReady
	/home/runner/work/yd-go/yd-go/yd.go:160 +0xdca
```

**Show daemon output**
```
yd-go11:37:00.597534 tools.go:135: I: Debugging enabled
yd-go11:37:00.597646 tools.go:94: D: cfg read: &{path:/home/andrei/.config/yd-go/default.cfg Conf:/home/andrei/.config/yandex-disk/config.cfg Theme:dark Notifications:true StartDaemon:true StopDaemon:false}
yd-go11:37:00.597654 yd.go:87: D: Local language is: en
yd-go11:37:00.599182 ydisk.go:204: D: yandex-disk executable is: /usr/bin/yandex-disk
yd-go11:37:00.599208 ydisk.go:171: D: Watch path added
yd-go11:37:00.599213 ydisk.go:218: D: New YDisk created and initialized. Path: /mnt/Data-s/Data/Yandex.Disk
yd-go11:37:00.599220 yd.go:165: D: event handler started
yd-go11:37:00.599269 ydisk.go:224: D: Event handler started
yd-go11:37:00.602880 ydisk.go:305: D: Daemon already started
yd-go11:37:00.699854 ydisk.go:246: D: Timer interval: 1
yd-go11:37:00.703764 ydisk.go:260: D: Change:  unknown > idle S true L 10 E false
yd-go11:37:00.703852 yd.go:283: D: Last synchronized length: 10
yd-go11:37:00.704935 yd.go:305: D: Change handled
yd-go11:37:02.701393 ydisk.go:246: D: Timer interval: 1
yd-go11:37:04.702420 ydisk.go:246: D: Timer interval: 2
yd-go11:37:08.702908 ydisk.go:246: D: Timer interval: 4
yd-go11:37:16.703993 ydisk.go:246: D: Timer interval: 8
yd-go11:37:18.056048 yd.go:100: D: Message: Yandex.Disk daemon output : Synchronization core status: idle
Path to Yandex.Disk directory: '/mnt/Data-s/Data/Yandex.Disk'
	Total: 508 GB
	Used: 494.94 GB
	Available: 13.06 GB
	Max file size: 50 GB
	Trash size: 163.53 GB

Last synchronized items:
	file: '***.mp4'
	file: '***.kdbx'
	file: '***.7z'

yd-go11:37:18.056966 ydisk.go:232: D: Event handler exited
yd-go11:37:18.056981 panic.go:884: D: event handler exited.
yd-go11:37:18.057436 tools.go:106: D: cfg saved: /home/andrei/.config/yd-go/default.cfg
panic: The name org.freedesktop.Notifications was not provided by any .service files

goroutine 24 [running]:
github.com/slytomcat/yd-go/notify.(*Notify).Send(0xc0000c80f0, {0x0?, 0x6a4200?}, {0xc0001e4040, 0x19}, {0xc0002bc000, 0x2ca})
	/home/runner/work/yd-go/yd-go/notify/notify.go:65 +0x2fd
main.onReady.func2({0xc0001e4040, 0x19}, {0xc0002bc000, 0x2ca})
	/home/runner/work/yd-go/yd-go/yd.go:101 +0x10d
main.eventHandler(0xc0000fa180, 0xc00002a100, 0xc0000c8190, 0xc0000c80f0)
	/home/runner/work/yd-go/yd-go/yd.go:208 +0x9e8
created by main.onReady
	/home/runner/work/yd-go/yd-go/yd.go:160 +0xdca
```

**Comment by avmaksimov** [comment]
Процесса больше нет в списке запущенных процессов и иконка "пропадает".

**Comment by slytomcat** [comment]
org.freedesktop.Notifications - сервис D-bus через который осуществляется вывод нотификаций (всплывающие сообщения). 
Для нормальной работы с уведомлениями в панели должен быть плагин уведомлений (именно он отвечает за вывод всплывающих сообщений и обеспеспечивает сервис org.freedesktop.Notifications).

Однако что-то действительно не так как должно быть. Вывод уведомлений можно вовсе отключить, и они вовсе не активируются если сервис  org.freedesktop.Notifications не найден. Но уведомления также используются для вывода About/Show daemon output (а при работе через d-bus и нет других механик что-то показать на экране, обычный диалог не открыть). И вот для них похоже нет другого выхода как просто отключить/деактивировать эти пункты меню когда сервис org.freedesktop.Notifications не найден.

Но с другой стороны, нужно как-то подсказать пользователю, что у него не хватает плагина уведомлений в панели. Подсказывать это через панику и краш приложения - согласен, не самое лучшее решение. 
Надо подумать над тем как вывести его в меню....

**Comment by avmaksimov** [comment]
А что за плагин я могу его поставить? У меня и Ferdium что-то не выдаёт уведомлений.

И, как вариант, предлагаю через что-то ещё выводить сообщения - но тут вам решать, конечно) Пока для меня Питон-версия лучше, несмотря на два значка.

**Comment by slytomcat** [comment]
У меня в XFCE он так и называется NotificationPlugin. 
Сделал пока вывод в лог ошибки при инициализации и добавил игнор ошибки при отправке уведомления.

**Comment by slytomcat** [comment]
Но про правильное уведомление для пользователя - надо подумать с точки здрения удобства, т.к. сейчас просто ничего не будет происходить при выборе About/Show daemon output в меню.

**Comment by slytomcat** [comment]
Правильное название пакета (судя по этому [ответу](https://unix.stackexchange.com/questions/535800/notification-daemon-completely-absent-although-libnotify-installed)) необходимого для поддержки интерфейса org.freedesktop.Notifications: `notification-daemon`

**Comment by slytomcat** [comment]
Закрыл т.к. не вижу смысла держать открытым без фидбека в течении 2-х месяцев.

**Comment by avmaksimov** [comment]
А вы ждали обратную связь?)) Я думал, вы для себя тут писали. На последней версии всё ОК показывается: и О программе, и вывод "Демона".

**Comment by slytomcat** [comment]
Странно так думать. 
Я вообще этой утилитой сам сейчас не пользуюсь, и продолжаю ее развивать и поддерживать именно для тех, кому она нужна.

**Comment by avmaksimov** [comment]
> Странно так думать.

Ага.. Сначала вы пишете, что вам надо подумать, а потом правильное название пакета)).



> Я вообще этой утилитой сам сейчас не пользуюсь, и продолжаю ее развивать и поддерживать именно для тех, кому она нужна.

Спасибо. Новая пока не дотягивает ещё лично для меня.
